# Generated by Django 3.2.4 on 2021-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210605_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot', models.CharField(max_length=50)),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('price2', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('anons_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('anons_ru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'MahsulotIndex',
                'verbose_name_plural': 'MahsulotlarIndex',
            },
        ),
    ]
